### ISSUE TITLE
How to set/override libvirt provider options?

### ISSUE THREAD

**Issue by stdevel** [ansible-community/molecule-vagrant#41] opened 2020-07-30 10:23 UTC
Hi folks,
for some Vagrant boxes (*generic/opensuse15* and *roboxes/opensuse15*) I need to override the `disk_bus` provider option in order to boot the VM. In a pure Vagrantfile, this is kinda easy:

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "generic/opensuse15"
  config.vm.box_version = "3.0.18"
  config.vm.provider :libvirt do |libvirt|
    libvirt.disk_bus = "sata"
  end
end
```

But I can't figure out how to set this in `molecule.yml`. From the molecule-vagrant documentation I understand that there are both `provider_options` and `provider_raw_config_args`, but I'm not very successful.

I tried several configuration arguments, currently my `molecule.yml` looks like this:

```yaml
---
dependency:
  name: galaxy
driver:
  name: vagrant
lint: |
    yamllint .
    ansible-lint
    flake8
platforms:
  - name: opensuse-leap15
    box: generic/opensuse15
    cpus: 2
    memory: 4096
    provider_options:
      disk_bus: "sata"
      libvirt.disk_bus: "sata"
      domain.disk_bus: "sata"
    provider_raw_config_args:
      - 'disk_bus = "sata"'
      - 'libvirt.disk_bus = "sata"'
      - 'domain.disk_bus = "sata"'
providers:
  - name: libvirt
    type: libvirt
    options:
      disk_bus: "sata"
      libvirt.disk_bus: "sata"
      domain.disk_bus: "sata"
provisioner:
  name: ansible
verifier:
  name: testinfra
```

Am I missing something?

**Comment by apatard** [comment] 2020-07-30 10:39
Which version of molecule-vagrant are you using ? it should be working with 0.3. Any older version are broken.


The current test suite is setting `nic_model_type` and not `disk_bus` (see https://github.com/ansible-community/molecule-vagrant/blob/master/molecule_vagrant/test/scenarios/molecule/provider_config_options/molecule.yml). I believe in should work in a same way.

**Comment by stdevel** [comment] 2020-07-30 11:11
Hey @apatard,
thanks for your fast reply!

I'm using version 0.3:

```shell
$ pip3 freeze |grep molecule-vagrant
molecule-vagrant==0.3
```

Thanks for the example, so setting `provider_options` per instance should work, also the format is quite the same. It just seems to ignore the `disk_bus` directive. Doing it manually works like a charm.

Any other ideas?

**Comment by apatard** [comment] 2020-07-30 11:31
Did you check the quotes ? 0.3 needs something like `disk_bus: '"sata"'`.

**Comment by apatard** [comment] 2020-08-04 09:45
did you manage to get it working ?
fwiw, here is a modified version of the molecule.yml of the test I was talking of:
```yaml
---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
lint:
  /bin/true
platforms:
- name: instance
  provider_options:
    disk_bus: '"sata"'
  box: debian/buster64
provisioner:
  name: ansible
verifier:
  name: ansible
```
and it seems to be working:
```xml
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2'/>
      <source file='/var/lib/libvirt/images/default_instance.img'/>
      <backingStore type='file' index='1'>
        <format type='qcow2'/>
        <source file='/var/lib/libvirt/images/debian-VAGRANTSLASH-buster64_vagrant_box_image_10.4.0.img'/>
        <backingStore/>
      </backingStore>
      <target dev='vda' bus='sata'/>
      <alias name='sata0-0-0'/>
      <address type='drive' controller='0' bus='0' target='0' unit='0'/>
    </disk>
```

**Comment by apatard** [comment] 2020-10-19 15:41
Hi.
@stdevel : Any news on this ?

**Comment by apatard** [comment] 2020-12-02 09:51
Hi,
I've provided a solution but no news about it fixing or not the issue for months. I'm going to close this issue. If the issue is still valid, please open a new bug. Thanks.

**Closed by apatard** 2020-12-02 09:51 UTC

**Comment by stdevel** [comment] 2020-12-05 08:02
Hi @apatard,
Sorry for ghosting you so long - totally missed to have a look at your suggestions. Thanks a lot for them!

I upgraded `molecule` and the `molecule-vagrant` module to the very latest versions:

```
molecule==3.2.0
molecule-docker==0.2.4
molecule-podman==0.3.0
molecule-vagrant==0.6
```

Also, I tried setting the `disk_bus` setting:

```
---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: instance
    provider_options:
      disk_bus: '"sata"'
    box: generic/opensuse15
provisioner:
  name: ansible
verifier:
  name: ansible
```

Anyhow, I'm getting the following error:

```
Path: <provider config: libvirt>
Line number: 179
Message: NoMethodError: undefined method `include?' for nil:NilClass
### 2020-12-05 09:01:05 ###
Vagrant failed to initialize at a very early stage:

There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: <provider config: libvirt>
Line number: 179
Message: NoMethodError: undefined method `include?' for nil:NilClass
```

I double-checked the `disk_bus` value and also tried both `'"sata"'` and `"'sata'"` - both seem not to work.
Am I missing something?

**Comment by apatard** [comment] 2020-12-07 14:03
@stdevel 
> Line number: 179
Message: NoMethodError: undefined method `include?' for nil:NilClass

oh, that's a different issue. don't know why it has not been caught during my tests and by the CI. Can you please open a new bug about this specific error to track it properly ?

> I double-checked the disk_bus value and also tried both '"sata"' and "'sata'" - both seem not to work

Can you check the ``~.cache/molecule/$role/$scenario/vagrant.yml`` content to see if the disk_bus is correctly set ?

**Comment by apatard** [comment] 2020-12-10 15:26
@stdevel the NoMethodError thing should be solved with 0.6.1.

**Comment by stdevel** [comment] 2020-12-23 08:46
Hi @apatard,
I cleared the molecule cache and upgraded the plugin to the latest version:

```shell
$ pip freeze|grep molecule
molecule==3.2.1
molecule-docker==0.2.4
molecule-podman==0.3.0
molecule-vagrant==0.6.1
```

Looks now I have another new issue:

```shell
$ molecule create
INFO     default scenario test matrix: dependency, create, prepare
INFO     Running default > dependency
WARNING  Skipping, missing the requirements file.
WARNING  Skipping, missing the requirements file.
INFO     Running default > create
WARNING  Skipping, instances already created.
INFO     Running default > prepare

PLAY [Prepare] *****************************************************************

TASK [Bootstrap python for Ansible] ********************************************
fatal: [suse-vm]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname suse-vm: Name or service not known", "unreachable": true}

PLAY RECAP *********************************************************************
suse-vm                    : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0


CRITICAL Ansible return code was 4, command was: ansible-playbook --inventory /home/christian/.cache/molecule/DUMMY/default/inventory --skip-tags molecule-notest,notest /usr/local/lib/python3.8/dist-packages/molecule_vagrant/playbooks/prepare.yml
```

Looks like the VM is not created anymore and therefore bootstrapping Python fails.

Best wishes,
Christian.

**Comment by apatard** [comment] 2021-01-05 08:19
Can you please open a new bug (and provide updated information) instead of always adding new errors in this bug ?
I hate to do that but to force things but if I manage to do it, I'm going to lock this bug.
